- name: ensure MySQL and dependencies are installed
  apt: pkg={{item}} state=present
  sudo: yes
  with_items:
      - python-mysqldb # the python mysqldb module is required
      - mysql-server 
      - mysql-client
      - libmysql-ruby 
      - libmysqlclient-dev

- name: ensure mysql is running and starts on boot
  service: name=mysql state=started enabled=true

# - name: Change root user password on first run
#   mysql_user: login_user=root
#               login_password=''
#               name=root
#               password={{ root_db_password }}
#               priv=*.*:ALL,GRANT
#               host={{ item }}
#   with_items:
#     - "{{ ansible_hostname }}"
#     - 127.0.0.1
#     - ::1
#     - localhost
#   ignore_errors: true

# - name: update mysql root password for all root accounts
#   mysql_user: name=root host={{ item }} password={{ root_db_password }} priv=*.*:ALL,GRANT
#   with_items:
#     - "{{ ansible_hostname }}"
#     - 127.0.0.1
#     - ::1
#     - localhost

# Need to do this for idempotency, see
# http://ansible.cc/docs/modules.html#mysql-user
# - name: update mysql root password for all root accounts
#   mysql_user: name=root host=localhost password={{ root_db_password }}

# - name: copy .my.cnf file with root password credentials
#   template: src=templates/root/.my.cnf dest=/root/.my.cnf owner=root mode=0600

# - name: update mysql root password for all root accounts
#   mysql_user: name=root host={{ item }} password={{ root_db_password }}
#   with_items:
#     - "{{ ansible_hostname }}"
#     - 127.0.0.1
#     - ::1

# - name: ensure anonymous users are not in the database
#   mysql_user: name='' host={{ item }} state=absent
#   with_items:
#     - localhost
#     - "{{ inventory_hostname }}"

# - name: remove the test database
#   mysql_db: name=test state=absent