- name: add PostgreSQL repository
  lineinfile: dest=/etc/apt/sources.list.d/pgdg.list
              line='deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main'
              create=yes
  sudo: yes

- name: add PostgreSQL repo key
  shell: wget --quiet -O - http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc | apt-key add -
  sudo: yes

- name: ensure apt-get is up to date with added postgres dependencies
  apt: update_cache=yes
  sudo: yes

- name: ensure PostgreSQL and dependencies are installed
  apt: pkg={{item}} state=present
  sudo: yes
  with_items:
      - postgresql-9.3
      - postgresql-contrib-9.3
      - libpq-dev
      - python-psycopg2

- name: add user to group to enable sudo
  action: user name=postgres groups=admin append=true
  sudo: yes

- name: create development/test databases
  postgresql_db: name={{item}}
                 encoding="UTF-8"
                 template="template0"
                 lc_collate='en_US.utf8'
                 lc_ctype='en_US.utf8'
  sudo: yes
  sudo_user: postgres
  with_items:
      - "{{dbname}}_development"
      - "{{dbname}}_test"

- name: ensure user has access to the new databases
  postgresql_user: db={{item}} name={{dbuser}} password={{dbpassword}} priv=ALL
  sudo: yes
  sudo_user: postgres
  with_items:
      - "{{dbname}}_development"
      - "{{dbname}}_test"

- name: ensure user does not have unnecessary privilege
  postgresql_user: name={{dbuser}} role_attr_flags=NOSUPERUSER,NOCREATEDB
  sudo: yes
  sudo_user: postgres
  when: dbuser_should_be_superuser != true

- name: ensure user is superuser
  postgresql_user: name={{dbuser}} role_attr_flags=CREATEDB,SUPERUSER
  sudo: yes
  sudo_user: postgres
  when: dbuser_should_be_superuser == true

- name: Ensure PostgreSQL is listening on the right port
  lineinfile: dest=/etc/postgresql/9.3/main/postgresql.conf
              regexp='^#?port\s*='
              line="port = 5440"
              state=present
  notify: restart postgresql
  sudo: yes
  sudo_user: postgres

- name: Ensure PostgreSQL is listening on all localhost
  lineinfile: dest=/etc/postgresql/9.3/main/postgresql.conf
              regexp='^#?listen_addresses\s*='
              line="listen_addresses = '*'"
              state=present
  notify: restart postgresql
  sudo: yes
  sudo_user: postgres

- name: Ensure PostgreSQL is listening to Vagrant
  lineinfile: dest=/etc/postgresql/9.3/main/pg_hba.conf
              regexp='host\s+all\s+all\s+127.0.0.1/32\s+md5'
              line='host all all 0.0.0.0/0 trust'
              insertbefore=BOF
  notify: restart postgresql
  sudo: yes
  sudo_user: postgres