- name: ensure PostgreSQL and dependencies are installed
  apt: pkg={{item}} state=present
  sudo: yes
  with_items:
      - postgresql
      - postgresql-contrib
      - libpq-dev
      - python-psycopg2

- name: add user to group to enable sudo
  action: user name=postgres groups=admin append=true
  sudo: yes

- name: create development/test databases
  postgresql_db: name={{item}}
  sudo: yes
  sudo_user: postgres
  with_items:
      - "{{dbname}}_development"
      - "{{dbname}}_test"

- name: ensure user has access to the new databases
  postgresql_user: db={{item}} name={{dbuser}} password={{dbpassword}} priv=ALL
  sudo: yes
  sudo_user: postgres
  with_items:
      - "{{dbname}}_development"
      - "{{dbname}}_test"

- name: ensure user does not have unnecessary privilege
  postgresql_user: name={{dbuser}} role_attr_flags=NOSUPERUSER,NOCREATEDB
  sudo: yes
  sudo_user: postgres