- name: ensure curl installed
  apt: pkg=curl state=present
  sudo: yes

- name: check rvm ruby version installed
  shell: /home/vagrant/.rvm/bin/rvm current
  register: ruby_exists
  ignore_errors: yes

- name: install RVM and required version of ruby
  sudo: yes
  shell: \curl -sSL https://get.rvm.io | bash -s stable --ruby={{ruby_version}}
  when: ruby_exists.stdout != 'ruby-{{ruby_version}}'

- name: fix permissions to allow for gem installation
  command: chown -R vagrant:vagrant /usr/local/rvm/gems/
  sudo: yes
  when: ruby_exists.stdout != 'ruby-{{ruby_version}}'