- name: ensure curl installed
  apt: pkg=curl state=present
  sudo: yes

- name: Configure no-ri no-rdoc
  lineinfile:
    dest=/etc/gemrc
    line="{{item}}"
    state=present
    insertafter=EOF
    create=True
  with_items:
    - "install: --no-rdoc --no-ri"
    - "update:  --no-rdoc --no-ri"
  sudo: yes

- name: set permissions on gemrc
  command: chown -R vagrant:vagrant /etc/gemrc
  sudo: yes

- name: check rvm ruby version installed
  shell: (test -f /usr/local/rvm/bin/rvm && /usr/local/rvm/bin/rvm current) || echo "system"
  register: ruby_exists

- name: install RVM
  sudo: yes
  shell: \curl -sSL https://get.rvm.io | bash -s stable
  when: ruby_exists.stdout != 'ruby-{{ruby_version}}'
  register: command_result
  failed_when: "'ERROR' in command_result.stderr"

- name: add vagrant user to rvm group
  action: user name=vagrant groups=rvm append=true
  sudo: yes
  when: ruby_exists.stdout != 'ruby-{{ruby_version}}'

- name: install required version of ruby
  sudo: yes
  shell: /usr/local/rvm/bin/rvm install {{ruby_version}}
  when: ruby_exists.stdout != 'ruby-{{ruby_version}}'

- name: fix permissions to allow for gem installation
  command: chown -R vagrant:vagrant /usr/local/rvm/gems/
  sudo: yes

#To Fix: https://github.com/travis-ci/travis-ci/issues/1806
- name: make sure we have a recent version of Bundler installed
  command: /usr/local/rvm/rubies/ruby-{{ruby_version}}/bin/gem install bundler -v '= {{bundler_version}}'
  sudo: yes
  when: ruby_exists.stdout != 'ruby-{{ruby_version}}'